# PostgreSQL. Versions 8.2 and up are supported.
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: BlogClone_development

test:
  <<: *default
  database: BlogClone_test

production:
  <<: *default
  database: BlogClone_production
  username: BlogClone
  password: <%= ENV['ALIASNERD_DATABASE_PASSWORD'] %>
